### ISSUE TITLE
MIX2  MIUI国际版修改DPI失败 未root  Android 8.0.0

### ISSUE THREAD

**Issue by 67373upupup** [zsh2401/www.atmb.top#7]
AutumnBox.Basic.Exceptions.AdbShellCommandFailedException: java.lang.SecurityException: Must hold permission android.permission.WRITE_SECURE_SETTINGS
	at android.os.Parcel.readException(Parcel.java:1954)
	at android.os.Parcel.readException(Parcel.java:1900)
	at android.view.IWindowManager$Stub$Proxy.setForcedDisplayDensityForUser(IWindowManager.java:1285)
	at com.android.commands.wm.Wm.runDisplayDensity(Wm.java:230)
	at com.android.commands.wm.Wm.onRun(Wm.java:98)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.wm.Wm.main(Wm.java:53)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)

   在 AutumnBox.Basic.Util.ThrowIf.ThrowIfShellExitCodeNotEqualsZero(IProcessBasedCommandResult result)
   在 AutumnBox.Basic.Device.Management.OS.WindowManager.set_Density(Int32 value)
   在 AutumnBox.CoreModules.Extensions.Poweron.EDpiModifier.Main(Dictionary`2 args)
   在 AutumnBox.OpenFramework.Running.ExtensionThread.Flow()

**Comment by singleNeuron** [comment]
找错地方了 去https://github.com/zsh2401/AutumnBox
